import logging
import os
from datetime import datetime

# this is standard file naming convention for log files, we can use the current date and time to create a unique log file name for each run of the application. This will help us to keep track of the logs generated by different runs of the application and avoid overwriting previous logs.
LOG_FILE=f"{datetime.now().strftime('%m_%d_%Y_%H_%M_%S')}.log" 
# log path is: current working directory/logs/log_file_name
logs_path=os.path.join(os.getcwd(),"logs",LOG_FILE)
#if the logs directory does not exist, create it
#the exist_ok=True parameter ensures that no error is raised if the directory already exists.
#it just keeps adding new log files to the existing logs directory
os.makedirs(logs_path, exist_ok=True)
LOG_FILE_PATH=os.path.join(logs_path,LOG_FILE)

logging.basicConfig(
    filename=LOG_FILE_PATH,
    level=logging.INFO,# this is the minimum level of severity that will be logged. In this case, it is set to INFO, which means that all messages with a severity level of INFO or higher (WARNING, ERROR, CRITICAL) will be logged.
    format="[%(asctime)s] %(lineno)d %(name)s - %(levelname)s - %(message)s",

)

if __name__=="__main__":
    logging.info("Logging has started.")

